"""
Mapa comuna → región, para resolver consultas a nivel regional.

El endpoint de MINSAL trae fk_region, pero es un identificador interno
que no corresponde a la numeración oficial de regiones. Por eso el mapeo
se mantiene aquí, derivado de la división político-administrativa
vigente (346 comunas, 16 regiones).

Las claves están normalizadas igual que en tool_minsal.normalizar_texto:
mayúsculas, sin tildes, Ñ preservada.
"""

COMUNA_A_REGION = {}

_REGIONES = {
    "ARICA Y PARINACOTA": ["ARICA", "CAMARONES", "PUTRE", "GENERAL LAGOS"],
    "TARAPACA": [
        "IQUIQUE", "ALTO HOSPICIO", "POZO ALMONTE", "CAMIÑA", "COLCHANE",
        "HUARA", "PICA",
    ],
    "ANTOFAGASTA": [
        "ANTOFAGASTA", "MEJILLONES", "SIERRA GORDA", "TALTAL", "CALAMA",
        "OLLAGUE", "SAN PEDRO DE ATACAMA", "TOCOPILLA", "MARIA ELENA",
    ],
    "ATACAMA": [
        "COPIAPO", "CALDERA", "TIERRA AMARILLA", "CHAÑARAL", "DIEGO DE ALMAGRO",
        "VALLENAR", "ALTO DEL CARMEN", "FREIRINA", "HUASCO",
    ],
    "COQUIMBO": [
        "LA SERENA", "COQUIMBO", "ANDACOLLO", "LA HIGUERA", "PAIGUANO",
        "VICUÑA", "ILLAPEL", "CANELA", "LOS VILOS", "SALAMANCA", "OVALLE",
        "COMBARBALA", "MONTE PATRIA", "PUNITAQUI", "RIO HURTADO",
    ],
    "VALPARAISO": [
        "VALPARAISO", "CASABLANCA", "CONCON", "JUAN FERNANDEZ", "PUCHUNCAVI",
        "QUINTERO", "VIÑA DEL MAR", "ISLA DE PASCUA", "LOS ANDES",
        "CALLE LARGA", "RINCONADA", "SAN ESTEBAN", "LA LIGUA", "CABILDO",
        "PAPUDO", "PETORCA", "ZAPALLAR", "QUILLOTA", "CALERA", "LA CALERA",
        "HIJUELAS", "LA CRUZ", "NOGALES", "SAN ANTONIO", "ALGARROBO",
        "CARTAGENA", "EL QUISCO", "EL TABO", "SANTO DOMINGO", "SAN FELIPE",
        "CATEMU", "LLAILLAY", "LLAY LLAY", "PANQUEHUE", "PUTAENDO",
        "SANTA MARIA", "QUILPUE", "LIMACHE", "OLMUE", "VILLA ALEMANA",
    ],
    "METROPOLITANA": [
        "SANTIAGO", "CERRILLOS", "CERRO NAVIA", "CONCHALI", "EL BOSQUE",
        "ESTACION CENTRAL", "HUECHURABA", "INDEPENDENCIA", "LA CISTERNA",
        "LA FLORIDA", "LA GRANJA", "LA PINTANA", "LA REINA", "LAS CONDES",
        "LO BARNECHEA", "LO ESPEJO", "LO PRADO", "MACUL", "MAIPU",
        "ÑUÑOA", "PEDRO AGUIRRE CERDA", "PEÑALOLEN", "PROVIDENCIA",
        "PUDAHUEL", "QUILICURA", "QUINTA NORMAL", "RECOLETA", "RENCA",
        "SAN JOAQUIN", "SAN MIGUEL", "SAN RAMON", "VITACURA",
        "PUENTE ALTO", "PIRQUE", "SAN JOSE DE MAIPO", "COLINA", "LAMPA",
        "TILTIL", "SAN BERNARDO", "BUIN", "CALERA DE TANGO", "PAINE",
        "MELIPILLA", "ALHUE", "CURACAVI", "MARIA PINTO", "SAN PEDRO",
        "TALAGANTE", "EL MONTE", "ISLA DE MAIPO", "PADRE HURTADO",
        "PEÑAFLOR",
    ],
    "OHIGGINS": [
        "RANCAGUA", "CODEGUA", "COINCO", "COLTAUCO", "DOÑIHUE", "GRANEROS",
        "LAS CABRAS", "MACHALI", "MALLOA", "MOSTAZAL",
        "SAN FRANCISCO DE MOSTAZAL", "OLIVAR", "PEUMO", "PICHIDEGUA",
        "QUINTA DE TILCOCO", "RENGO", "REQUINOA", "SAN VICENTE",
        "PICHILEMU", "LA ESTRELLA", "LITUECHE", "MARCHIHUE", "NAVIDAD",
        "PAREDONES", "SAN FERNANDO", "CHEPICA", "CHIMBARONGO", "LOLOL",
        "NANCAGUA", "PALMILLA", "PERALILLO", "PLACILLA", "PUMANQUE",
        "SANTA CRUZ",
    ],
    "MAULE": [
        "TALCA", "CONSTITUCION", "CUREPTO", "EMPEDRADO", "MAULE", "PELARCO",
        "PENCAHUE", "RIO CLARO", "SAN CLEMENTE", "SAN RAFAEL", "CAUQUENES",
        "CHANCO", "PELLUHUE", "CURICO", "HUALAÑE", "LICANTEN", "MOLINA",
        "RAUCO", "ROMERAL", "SAGRADA FAMILIA", "TENO", "VICHUQUEN",
        "LINARES", "COLBUN", "LONGAVI", "PARRAL", "RETIRO", "SAN JAVIER",
        "VILLA ALEGRE", "YERBAS BUENAS",
    ],
    "ÑUBLE": [
        "CHILLAN", "CHILLAN VIEJO", "EL CARMEN", "PEMUCO", "PINTO",
        "QUILLON", "SAN IGNACIO", "YUNGAY", "QUIRIHUE", "COBQUECURA",
        "COELEMU", "NINHUE", "PORTEZUELO", "RANQUIL", "TREHUACO",
        "SAN CARLOS", "COIHUECO", "ÑIQUEN", "SAN FABIAN", "SAN NICOLAS",
    ],
    "BIOBIO": [
        "CONCEPCION", "CORONEL", "CHIGUAYANTE", "FLORIDA", "HUALQUI",
        "LOTA", "PENCO", "SAN PEDRO DE LA PAZ", "SANTA JUANA", "TALCAHUANO",
        "TOME", "HUALPEN", "LEBU", "ARAUCO", "CAÑETE", "CONTULMO",
        "CURANILAHUE", "LOS ALAMOS", "TIRUA", "LOS ANGELES", "ANTUCO",
        "CABRERO", "LAJA", "MULCHEN", "NACIMIENTO", "NEGRETE", "QUILACO",
        "QUILLECO", "SAN ROSENDO", "SANTA BARBARA", "TUCAPEL", "YUMBEL",
        "ALTO BIOBIO",
    ],
    "ARAUCANIA": [
        "TEMUCO", "CARAHUE", "CUNCO", "CURARREHUE", "FREIRE", "GALVARINO",
        "GORBEA", "LAUTARO", "LONCOCHE", "MELIPEUCO", "NUEVA IMPERIAL",
        "PADRE LAS CASAS", "PERQUENCO", "PITRUFQUEN", "PUCON", "SAAVEDRA",
        "TEODORO SCHMIDT", "TOLTEN", "VILCUN", "VILLARRICA", "CHOLCHOL",
        "ANGOL", "COLLIPULLI", "CURACAUTIN", "ERCILLA", "LONQUIMAY",
        "LOS SAUCES", "LUMACO", "PUREN", "RENAICO", "TRAIGUEN", "VICTORIA",
    ],
    "LOS RIOS": [
        "VALDIVIA", "CORRAL", "LANCO", "LOS LAGOS", "MAFIL", "MARIQUINA",
        "PAILLACO", "PANGUIPULLI", "LA UNION", "FUTRONO", "LAGO RANCO",
        "RIO BUENO",
    ],
    "LOS LAGOS": [
        "PUERTO MONTT", "CALBUCO", "COCHAMO", "FRESIA", "FRUTILLAR",
        "LOS MUERMOS", "LLANQUIHUE", "MAULLIN", "PUERTO VARAS", "CASTRO",
        "ANCUD", "CHONCHI", "CURACO DE VELEZ", "DALCAHUE", "PUQUELDON",
        "QUEILEN", "QUELLON", "QUEMCHI", "QUINCHAO", "OSORNO",
        "PUERTO OCTAY", "PURRANQUE", "PUYEHUE", "RIO NEGRO",
        "SAN JUAN DE LA COSTA", "SAN PABLO", "CHAITEN", "FUTALEUFU",
        "HUALAIHUE", "PALENA",
    ],
    "AYSEN": [
        "COYHAIQUE", "LAGO VERDE", "AYSEN", "PUERTO AYSEN", "CISNES",
        "GUAITECAS", "COCHRANE", "OHIGGINS", "TORTEL", "CHILE CHICO",
        "RIO IBAÑEZ",
    ],
    "MAGALLANES": [
        "PUNTA ARENAS", "LAGUNA BLANCA", "RIO VERDE", "SAN GREGORIO",
        "CABO DE HORNOS", "ANTARTICA", "PORVENIR", "PRIMAVERA", "TIMAUKEL",
        "NATALES", "PUERTO NATALES", "TORRES DEL PAINE",
    ],
}

for _region, _comunas in _REGIONES.items():
    for _c in _comunas:
        COMUNA_A_REGION[_c] = _region


# Formas en que el usuario puede nombrar una región. La clave normalizada
# apunta al nombre canónico usado arriba.
ALIAS_REGION = {
    "REGION METROPOLITANA": "METROPOLITANA", "RM": "METROPOLITANA",
    "METROPOLITANA": "METROPOLITANA", "SANTIAGO METROPOLITANA": "METROPOLITANA",
    "REGION DE VALPARAISO": "VALPARAISO", "VALPARAISO": "VALPARAISO",
    "QUINTA REGION": "VALPARAISO", "V REGION": "VALPARAISO",
    "REGION DEL BIOBIO": "BIOBIO", "BIOBIO": "BIOBIO", "BIO BIO": "BIOBIO",
    "REGION DE LA ARAUCANIA": "ARAUCANIA", "ARAUCANIA": "ARAUCANIA",
    "REGION DE LOS LAGOS": "LOS LAGOS", "LOS LAGOS": "LOS LAGOS",
    "REGION DE LOS RIOS": "LOS RIOS", "LOS RIOS": "LOS RIOS",
    "REGION DE COQUIMBO": "COQUIMBO", "COQUIMBO": "COQUIMBO",
    "REGION DE ATACAMA": "ATACAMA", "ATACAMA": "ATACAMA",
    "REGION DE ANTOFAGASTA": "ANTOFAGASTA", "ANTOFAGASTA": "ANTOFAGASTA",
    "REGION DE TARAPACA": "TARAPACA", "TARAPACA": "TARAPACA",
    "REGION DE ARICA Y PARINACOTA": "ARICA Y PARINACOTA",
    "ARICA Y PARINACOTA": "ARICA Y PARINACOTA", "ARICA": "ARICA Y PARINACOTA",
    "REGION DEL MAULE": "MAULE", "MAULE": "MAULE",
    "REGION DE ÑUBLE": "ÑUBLE", "ÑUBLE": "ÑUBLE",
    "REGION DE OHIGGINS": "OHIGGINS", "OHIGGINS": "OHIGGINS",
    "REGION DEL LIBERTADOR BERNARDO OHIGGINS": "OHIGGINS",
    "SEXTA REGION": "OHIGGINS", "VI REGION": "OHIGGINS",
    "REGION DE AYSEN": "AYSEN", "AYSEN": "AYSEN",
    "REGION DE MAGALLANES": "MAGALLANES", "MAGALLANES": "MAGALLANES",
}


def region_de(comuna_normalizada: str) -> str | None:
    return COMUNA_A_REGION.get(comuna_normalizada)


def canonizar_region(texto_normalizado: str) -> str | None:
    """Resuelve el nombre que escribió el usuario al nombre canónico."""
    return ALIAS_REGION.get(texto_normalizado)